### ISSUE TITLE
WinJS suitability for web apps

### ISSUE THREAD

**Issue by SteveALee** [gleborgne/winjscontrib#4]
In your [first blog post on WinJS and WInJS Contrib](http://mcnextpost.com/2015/04/15/why-winjs-can-be-good-front-end-framework/) you raise some questions about using WinJS 'for web'. While I had realised the UI style is native app like rather than web like, I had not grokked the possibility of many small fetches / round trips which is obviously an issue in low bandwidth and also for device power use. 

But perhaps that is only some APIs. The team certainly admit there are no major uses on WInJS on the web

To be honest my last real experience of WinJS was during Windows 8.0 beta and some surprisingly poor MSDN docs - until I discovered [Kraig' Brockschmidt's excellent book](http://blogs.msdn.com/b/microsoft_press/archive/2014/04/08/free-ebook-programming-windows-store-apps-with-html-css-and-javascript-second-edition.aspx). Having researched all the various main current frameworks I decided on WinJS for the reason you describe in you posts and a few more. However your comments have given me cause to pause for thought.

My current plan is to eventually have hybrid mobile/tablet apps, no doubt using Cordova with local assets, but I planned to start with a browser based HTML app served from a remote server. I've decided on the node (with the new VisualStudio extensions), T3 and bacon as the key technologies, plus some web components (perhaps using your techniques).

Can you expand at all on your thoughts on the issues about using WinJS for HTML apps server over the the web?

**Comment by gleborgne** [comment]
Hi Steve,

Thanks for your feedback. It's really appreciated.

Lets expand a little on that. You could use WinJS for web applications. It will work. The problem is about the frictions you may encounter. First WinJS is a fat framework. Things are all built into one huge file. If you want to make it leaner, you have to fork the project and set a custom build. This is insane to me. There is an issue on Github for asking them to split into multiple files.

Then, WinJS fragment/page is what makes it really shine because you really think and split your work in components, but unfortunately it has not been designed for web. In a webcontext, you will probably want to bundle one or many pages in order to load them at once at application startup. There is nothing built in WinJS to help you do that. Event worse, every implementation details are sealed within WinJS and you may have a hard time hacking WinJS to implement this kind of scenarios.

One other scenario that comes to mind is about managing application state with urls, a system of router. That's something often required for web applications, and their is nothing to do that in WinJS. You could implement one on top of navigation by using push state but it is up to you.

Their is no silver bullet. You will have to trade between the different constraints on your project. If your application have to work on web and behave like a website, WinJS may not be the best fit.

Guillaume

**Comment by SteveALee** [comment]
Thanks Guillaume, that is all useful. As you so there is no silver bullet :)

Re fragment loading - sometimes you actually want progressive download, say if pages are large. The point is, as you indicate,  it should be under the developer's control.

Every library has pros and cons. And i'm still going to continue. I like you saying you have fun with it :) The web components 'sugar' looks interesting to me too.

I just realised CSS grid is an issue as not all browser yet support it. But there is at least a polyfil to try

**Comment by gleborgne** [comment]
I'm ranting on WinJS because it does not evolve much lastly, but I still love it :)
I especially love the fact that I stay in control of almost everything.

for grid, 95% of the time, you can use flex instead of grid. display:flex has a pretty good support in mobile browsers now (depends on Android versions you want to support). It's better to look that way before adding a polyfill for grid

**Comment by SteveALee** [comment]
Thanks for the tip.
Perhaps there will be exciting news at //build/ re WInJS? ;)
I'm disappointed that ll universal app samples are c# so far

**Comment by gleborgne** [comment]
Regarding the sessions agenda, I don't expect any breaking news about WinJS

**Comment by SteveALee** [comment]
Na, me neither. Just wishful thinking. Plus I'm only streaming.
